server:
  port: 8800
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
  mapper-locations: classpath:com/atguigu/*/mapper/xml/*.xml
spring:
  redis:
    host: 43.207.192.101
    port: 6379
    database: 0
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 5
        min-idle: 0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.207.192.101:3306/guigu-oa?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: 12345678

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+9
  knife4j:
    # 开启增强配置
    enable: true
    setting:
      # 是否开启动态参数调试功能,默认关闭
      enableDynamicParameter: true
